version: '2'

networks:
        ice:

services:
        head:
                build: mumble-head
                depends_on: 
                        - data_volume
                volumes_from: 
                        - data_volume
                ports:
                        - "64738:64738"
                        - "64738:64738/udp"
                restart: always
                networks:
                        - ice

        data_volume:
                build: mumble-volume

